BackEnd-Rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  resources :edificios, only: [:index, :show, :destroy]
  resources :horas, only: [:index, :show, :destroy]
  resources :horarios, only: [:index, :show, :destroy, :create]
  

  resources :students, only: [:index, :show, :destroy, :create, :update] 
  resources :books, only: [:index, :show, :destroy, :create, :update] do
    collection do
      get 'by_user/:student_id', to: 'books#by_user', as: 'by_user'
      get 'by_technician/:tecnico_id', to: 'books#by_technician', as: 'by_technician'
      put 'update_est_res_to_true/:id', to: 'books#update_est_res_to_true'
    end
  end
  resources :floors, only: [:index, :show, :destroy]
  resources :tecnicos, only: [:index, :show, :destroy, :create]
  
  resources :rooms, only: [:index, :show, :destroy, :create, :update] do
    collection do
      get 'by_disponible', to: 'rooms#by_disponible'
      get 'by_floor/:floor_id', to: 'rooms#by_floor', as: 'by_floor'
    end
    member do
      get 'horario'
    end
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

BackEnd-Rails/app/models/administrator.rb
class Administrator < ApplicationRecord
end

BackEnd-Rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

BackEnd-Rails/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :Student
  belongs_to :Tecnico
  belongs_to :Room

  # Callback que se ejecuta antes de guardar una instancia de Book
  before_save :actualizar_estado

  def actualizar_estado
    current_time_with_zone = Time.zone.now
    if current_time_with_zone < self.HOR_INI_RES
      self.HOR_TIM_RES = "POR EMPEZAR"
    elsif current_time_with_zone.between?(self.HOR_INI_RES, self.HOR_FIN_RES)
      self.EST_TIM_RES = "EN CURSO"
    else
      self.EST_TIM_RES = "TERMINADO"
    end
  end
  
end

BackEnd-Rails/app/models/dia_semana.rb
class DiaSemana < ApplicationRecord
    has_many :intervalo_horarios
end

BackEnd-Rails/app/models/edificio.rb
class Edificio < ApplicationRecord
    has_many :room
end

BackEnd-Rails/app/models/floor.rb
class Floor < ApplicationRecord
    has_many :room
end

BackEnd-Rails/app/models/hora.rb
class Hora < ApplicationRecord
    has_many :horarios
end

BackEnd-Rails/app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :hora
  belongs_to :room
end

BackEnd-Rails/app/models/horario_academico.rb
class HorarioAcademico < ApplicationRecord
  belongs_to :Room
  has_many :intervalo_horarios
end

BackEnd-Rails/app/models/intervalo_horario.rb
class IntervaloHorario < ApplicationRecord
  belongs_to :horario_academico
  belongs_to :dia_semana
end

BackEnd-Rails/app/models/room.rb
class Room < ApplicationRecord
  belongs_to :Floor
  belongs_to :Edificio
  has_many :horarios
  has_many :horarios_academicos
end

BackEnd-Rails/app/models/student.rb
class Student < ApplicationRecord
end

BackEnd-Rails/app/models/tecnico.rb
class Tecnico < ApplicationRecord
end

BackEnd-Rails/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

BackEnd-Rails/app/controllers/floors_controller.rb
class FloorsController < ApplicationController
  before_action :set_floor, only: %i[ show edit update destroy ]

  # GET /floors or /floors.json
  def index
    @floors = Floor.all
    render json: @floors
  end

  # GET /floors/1 or /floors/1.json
  def show
    render json: @floor
  end

  # GET /floors/new
  def new
    @floor = Floor.new
  end

  # GET /floors/1/edit
  def edit
  end

  # POST /floors or /floors.json
  def create
    @floor = Floor.new(floor_params)

    if @floor.save
      render json: @floor, status: :created, location: @floor
    else
      render json: @floor.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /floors/1 or /floors/1.json
  def update
    if @floor.update(floor_params)
      render json: @floor
    else
      render json: @floor.errors, status: :unprocessable_entity
    end
  end

  # DELETE /floors/1 or /floors/1.json
  def destroy
    @floor.destroy!
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_floor
      @floor = Floor.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def floor_params
      params.require(:floor).permit(:NOM_PIS, :DES_PIS, :IMG_PIS)
    end
end

BackEnd-Rails/app/helpers/books_helper.rb
module BooksHelper
end

BackEnd-Rails/app/helpers/edificios_helper.rb
module EdificiosHelper
end

BackEnd-Rails/app/helpers/floors_helper.rb
module FloorsHelper
end

BackEnd-Rails/app/helpers/horarios_helper.rb
module HorariosHelper
end

BackEnd-Rails/app/helpers/horas_helper.rb
module HorasHelper
end

BackEnd-Rails/app/helpers/rooms_helper.rb
module RoomsHelper
end

BackEnd-Rails/app/helpers/students_helper.rb
module StudentsHelper
end

BackEnd-Rails/app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

BackEnd-Rails/app/views/floors/_floor.html.erb
<div id="<%= dom_id floor %>">
  <p>
    <strong>Nom pis:</strong>
    <%= floor.NOM_PIS %>
  </p>

  <p>
    <strong>Des pis:</strong>
    <%= floor.DES_PIS %>
  </p>

  <p>
    <strong>Img pis:</strong>
    <%= floor.IMG_PIS %>
  </p>

</div>

BackEnd-Rails/app/views/floors/_form.html.erb
<%= form_with(model: floor) do |form| %>
  <% if floor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(floor.errors.count, "error") %> prohibited this floor from being saved:</h2>

      <ul>
        <% floor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :NOM_PIS, style: "display: block" %>
    <%= form.text_field :NOM_PIS %>
  </div>

  <div>
    <%= form.label :DES_PIS, style: "display: block" %>
    <%= form.text_field :DES_PIS %>
  </div>

  <div>
    <%= form.label :IMG_PIS, style: "display: block" %>
    <%= form.text_field :IMG_PIS %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

BackEnd-Rails/app/views/floors/edit.html.erb
<h1>Editing floor</h1>

<%= render "form", floor: @floor %>

<br>

<div>
  <%= link_to "Show this floor", @floor %> |
  <%= link_to "Back to floors", floors_path %>
</div>

BackEnd-Rails/app/views/floors/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Floors</h1>

<div id="floors">
  <% @floors.each do |floor| %>
    <%= render floor %>
    <p>
      <%= link_to "Show this floor", floor %>
    </p>
  <% end %>
</div>

<%= link_to "New floor", new_floor_path %>

BackEnd-Rails/app/views/floors/new.html.erb
<h1>New floor</h1>

<%= render "form", floor: @floor %>

<br>

<div>
  <%= link_to "Back to floors", floors_path %>
</div>

BackEnd-Rails/app/views/floors/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @floor %>

<div>
  <%= link_to "Edit this floor", edit_floor_path(@floor) %> |
  <%= link_to "Back to floors", floors_path %>

  <%= button_to "Destroy this floor", @floor, method: :delete %>
</div>