BackEnd-Rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  resources :edificios, only: [:index, :show, :destroy]
  resources :horas, only: [:index, :show, :destroy]
  resources :horarios, only: [:index, :show, :destroy, :create]
  

  resources :students, only: [:index, :show, :destroy, :create, :update] 
  resources :books, only: [:index, :show, :destroy, :create, :update] do
    collection do
      get 'by_user/:student_id', to: 'books#by_user', as: 'by_user'
      get 'by_technician/:tecnico_id', to: 'books#by_technician', as: 'by_technician'
      put 'update_est_res_to_true/:id', to: 'books#update_est_res_to_true'
    end
  end
  resources :floors, only: [:index, :show, :destroy]
  resources :tecnicos, only: [:index, :show, :destroy, :create]
  
  resources :rooms, only: [:index, :show, :destroy, :create, :update] do
    collection do
      get 'by_disponible', to: 'rooms#by_disponible'
      get 'by_floor/:floor_id', to: 'rooms#by_floor', as: 'by_floor'
    end
    member do
      get 'horario'
    end
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

BackEnd-Rails/app/models/administrator.rb
class Administrator < ApplicationRecord
end

BackEnd-Rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

BackEnd-Rails/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :Student
  belongs_to :Tecnico
  belongs_to :Room

  # Callback que se ejecuta antes de guardar una instancia de Book
  before_save :actualizar_estado

  def actualizar_estado
    current_time_with_zone = Time.zone.now
    if current_time_with_zone < self.HOR_INI_RES
      self.HOR_TIM_RES = "POR EMPEZAR"
    elsif current_time_with_zone.between?(self.HOR_INI_RES, self.HOR_FIN_RES)
      self.EST_TIM_RES = "EN CURSO"
    else
      self.EST_TIM_RES = "TERMINADO"
    end
  end
  
end

BackEnd-Rails/app/models/dia_semana.rb
class DiaSemana < ApplicationRecord
    has_many :intervalo_horarios
end

BackEnd-Rails/app/models/edificio.rb
class Edificio < ApplicationRecord
    has_many :room
end

BackEnd-Rails/app/models/floor.rb
class Floor < ApplicationRecord
    has_many :room
end

BackEnd-Rails/app/models/hora.rb
class Hora < ApplicationRecord
    has_many :horarios
end

BackEnd-Rails/app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :hora
  belongs_to :room
end

BackEnd-Rails/app/models/horario_academico.rb
class HorarioAcademico < ApplicationRecord
  belongs_to :Room
  has_many :intervalo_horarios
end

BackEnd-Rails/app/models/intervalo_horario.rb
class IntervaloHorario < ApplicationRecord
  belongs_to :horario_academico
  belongs_to :dia_semana
end

BackEnd-Rails/app/models/room.rb
class Room < ApplicationRecord
  belongs_to :Floor
  belongs_to :Edificio
  has_many :horarios
  has_many :horarios_academicos
end

BackEnd-Rails/app/models/student.rb
class Student < ApplicationRecord
end

BackEnd-Rails/app/models/tecnico.rb
class Tecnico < ApplicationRecord
end

BackEnd-Rails/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

BackEnd-Rails/app/controllers/tecnicos_controller.rb
class TecnicosController < ApplicationController
  before_action :set_tecnico, only: %i[ show update destroy ]

  # GET /tecnicos
  def index
    @tecnicos = Tecnico.all

    render json: @tecnicos
  end

  # GET /tecnicos/1
  def show
    render json: @tecnico
  end

  # POST /tecnicos
  def create
    @tecnico = Tecnico.new(tecnico_params)

    if @tecnico.save
      render json: @tecnico, status: :created, location: @tecnico
    else
      render json: @tecnico.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tecnicos/1
  def update
    if @tecnico.update(tecnico_params)
      render json: @tecnico
    else
      render json: @tecnico.errors, status: :unprocessable_entity
    end
  end

  # DELETE /tecnicos/1
  def destroy
    @tecnico.destroy!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tecnico
      @tecnico = Tecnico.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tecnico_params
      params.require(:tecnico).permit(:NOM_TEC, :APE_TEC,:NOM_USER_TEC, :FEC_NAC_TEC, :FEC_ING_TEC, :CON_TEC)
    end
end

BackEnd-Rails/app/helpers/books_helper.rb
module BooksHelper
end

BackEnd-Rails/app/helpers/edificios_helper.rb
module EdificiosHelper
end

BackEnd-Rails/app/helpers/floors_helper.rb
module FloorsHelper
end

BackEnd-Rails/app/helpers/horarios_helper.rb
module HorariosHelper
end

BackEnd-Rails/app/helpers/horas_helper.rb
module HorasHelper
end

BackEnd-Rails/app/helpers/rooms_helper.rb
module RoomsHelper
end

BackEnd-Rails/app/helpers/students_helper.rb
module StudentsHelper
end

BackEnd-Rails/app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

BackEnd-Rails/app/views/tecnicos/_form.html.erb
<%= form_with(model: tecnico) do |form| %>
  <% if tecnico.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tecnico.errors.count, "error") %> prohibited this tecnico from being saved:</h2>

      <ul>
        <% tecnico.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :NOM_TEC, style: "display: block" %>
    <%= form.text_field :NOM_TEC %>
  </div>

  <div>
    <%= form.label :APE_TEC, style: "display: block" %>
    <%= form.text_field :APE_TEC %>
  </div>

  <div>
    <%= form.label :FEC_NAC_TEC, style: "display: block" %>
    <%= form.text_field :FEC_NAC_TEC %>
  </div>

  <div>
    <%= form.label :FEC_ING_TEC, style: "display: block" %>
    <%= form.date_field :FEC_ING_TEC %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

BackEnd-Rails/app/views/tecnicos/_tecnico.html.erb
<div id="<%= dom_id tecnico %>">
  <p>
    <strong>Nom tec:</strong>
    <%= tecnico.NOM_TEC %>
  </p>

  <p>
    <strong>Ape tec:</strong>
    <%= tecnico.APE_TEC %>
  </p>

  <p>
    <strong>Fec nac tec:</strong>
    <%= tecnico.FEC_NAC_TEC %>
  </p>

  <p>
    <strong>Fec ing tec:</strong>
    <%= tecnico.FEC_ING_TEC %>
  </p>

</div>

BackEnd-Rails/app/views/tecnicos/edit.html.erb
<h1>Editing tecnico</h1>

<%= render "form", tecnico: @tecnico %>

<br>

<div>
  <%= link_to "Show this tecnico", @tecnico %> |
  <%= link_to "Back to tecnicos", tecnicos_path %>
</div>

BackEnd-Rails/app/views/tecnicos/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tecnicos</h1>

<div id="tecnicos">
  <% @tecnicos.each do |tecnico| %>
    <%= render tecnico %>
    <p>
      <%= link_to "Show this tecnico", tecnico %>
    </p>
  <% end %>
</div>

<%= link_to "New tecnico", new_tecnico_path %>

BackEnd-Rails/app/views/tecnicos/new.html.erb
<h1>New tecnico</h1>

<%= render "form", tecnico: @tecnico %>

<br>

<div>
  <%= link_to "Back to tecnicos", tecnicos_path %>
</div>

BackEnd-Rails/app/views/tecnicos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tecnico %>

<div>
  <%= link_to "Edit this tecnico", edit_tecnico_path(@tecnico) %> |
  <%= link_to "Back to tecnicos", tecnicos_path %>

  <%= button_to "Destroy this tecnico", @tecnico, method: :delete %>
</div>