BackEnd-Rails/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  
  resources :edificios, only: [:index, :show, :destroy]
  resources :horas, only: [:index, :show, :destroy]
  resources :horarios, only: [:index, :show, :destroy, :create]
  

  resources :students, only: [:index, :show, :destroy, :create, :update] 
  resources :books, only: [:index, :show, :destroy, :create, :update] do
    collection do
      get 'by_user/:student_id', to: 'books#by_user', as: 'by_user'
      get 'by_technician/:tecnico_id', to: 'books#by_technician', as: 'by_technician'
      put 'update_est_res_to_true/:id', to: 'books#update_est_res_to_true'
    end
  end
  resources :floors, only: [:index, :show, :destroy]
  resources :tecnicos, only: [:index, :show, :destroy, :create]
  
  resources :rooms, only: [:index, :show, :destroy, :create, :update] do
    collection do
      get 'by_disponible', to: 'rooms#by_disponible'
      get 'by_floor/:floor_id', to: 'rooms#by_floor', as: 'by_floor'
    end
    member do
      get 'horario'
    end
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

BackEnd-Rails/app/models/administrator.rb
class Administrator < ApplicationRecord
end

BackEnd-Rails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

BackEnd-Rails/app/models/book.rb
class Book < ApplicationRecord
  belongs_to :Student
  belongs_to :Tecnico
  belongs_to :Room

  # Callback que se ejecuta antes de guardar una instancia de Book
  before_save :actualizar_estado

  def actualizar_estado
    current_time_with_zone = Time.zone.now
    if current_time_with_zone < self.HOR_INI_RES
      self.HOR_TIM_RES = "POR EMPEZAR"
    elsif current_time_with_zone.between?(self.HOR_INI_RES, self.HOR_FIN_RES)
      self.EST_TIM_RES = "EN CURSO"
    else
      self.EST_TIM_RES = "TERMINADO"
    end
  end
  
end

BackEnd-Rails/app/models/dia_semana.rb
class DiaSemana < ApplicationRecord
    has_many :intervalo_horarios
end

BackEnd-Rails/app/models/edificio.rb
class Edificio < ApplicationRecord
    has_many :room
end

BackEnd-Rails/app/models/floor.rb
class Floor < ApplicationRecord
    has_many :room
end

BackEnd-Rails/app/models/hora.rb
class Hora < ApplicationRecord
    has_many :horarios
end

BackEnd-Rails/app/models/horario.rb
class Horario < ApplicationRecord
  belongs_to :hora
  belongs_to :room
end

BackEnd-Rails/app/models/horario_academico.rb
class HorarioAcademico < ApplicationRecord
  belongs_to :Room
  has_many :intervalo_horarios
end

BackEnd-Rails/app/models/intervalo_horario.rb
class IntervaloHorario < ApplicationRecord
  belongs_to :horario_academico
  belongs_to :dia_semana
end

BackEnd-Rails/app/models/room.rb
class Room < ApplicationRecord
  belongs_to :Floor
  belongs_to :Edificio
  has_many :horarios
  has_many :horarios_academicos
end

BackEnd-Rails/app/models/student.rb
class Student < ApplicationRecord
end

BackEnd-Rails/app/models/tecnico.rb
class Tecnico < ApplicationRecord
end

BackEnd-Rails/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

BackEnd-Rails/app/controllers/horarios_controller.rb
class HorariosController < ApplicationController
  before_action :set_horario, only: %i[ show edit update destroy ]

  # GET /horarios or /horarios.json
  def index
    @horarios = Horario.all
    render json: @horarios
  end

  # GET /horarios/1 or /horarios/1.json
  def show
    render json: @horario
  end

  # GET /horarios/new
  def new
    @horario = Horario.new
  end

  # GET /horarios/1/edit
  def edit
  end

  # POST /horarios or /horarios.json
  def create
    @horario = Horario.new(horario_params)

      if @horario.save
        render json :show, status: :created, location: @horario
      else
        render json: @horario.errors, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /horarios/1 or /horarios/1.json
  def update
      if @horario.update(horario_params)
        render json :show, status: :ok, location: @horario
      else
        render json: @horario.errors, status: :unprocessable_entity
      end
  end

  # DELETE /horarios/1 or /horarios/1.json
  def destroy
    @horario.destroy!
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_horario
      @horario = Horario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def horario_params
      params.require(:horario).permit(:hora_id, :Lunes, :Martes, :Miercoles, :Jueves, :Viernes, :room_id)
    end
end

BackEnd-Rails/app/helpers/books_helper.rb
module BooksHelper
end

BackEnd-Rails/app/helpers/edificios_helper.rb
module EdificiosHelper
end

BackEnd-Rails/app/helpers/floors_helper.rb
module FloorsHelper
end

BackEnd-Rails/app/helpers/horarios_helper.rb
module HorariosHelper
end

BackEnd-Rails/app/helpers/horas_helper.rb
module HorasHelper
end

BackEnd-Rails/app/helpers/rooms_helper.rb
module RoomsHelper
end

BackEnd-Rails/app/helpers/students_helper.rb
module StudentsHelper
end

BackEnd-Rails/app/helpers/tecnicos_helper.rb
module TecnicosHelper
end

BackEnd-Rails/app/views/horarios/_form.html.erb
<%= form_with(model: horario) do |form| %>
  <% if horario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(horario.errors.count, "error") %> prohibited this horario from being saved:</h2>

      <ul>
        <% horario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :hora_id, style: "display: block" %>
    <%= form.text_field :hora_id %>
  </div>

  <div>
    <%= form.label :Lunes, style: "display: block" %>
    <%= form.text_field :Lunes %>
  </div>

  <div>
    <%= form.label :Martes, style: "display: block" %>
    <%= form.text_field :Martes %>
  </div>

  <div>
    <%= form.label :Miercoles, style: "display: block" %>
    <%= form.text_field :Miercoles %>
  </div>

  <div>
    <%= form.label :Jueves, style: "display: block" %>
    <%= form.text_field :Jueves %>
  </div>

  <div>
    <%= form.label :Viernes, style: "display: block" %>
    <%= form.text_field :Viernes %>
  </div>

  <div>
    <%= form.label :room_id, style: "display: block" %>
    <%= form.text_field :room_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

BackEnd-Rails/app/views/horarios/_horario.html.erb
<div id="<%= dom_id horario %>">
  <p>
    <strong>Hora:</strong>
    <%= horario.hora_id %>
  </p>

  <p>
    <strong>Lunes:</strong>
    <%= horario.Lunes %>
  </p>

  <p>
    <strong>Martes:</strong>
    <%= horario.Martes %>
  </p>

  <p>
    <strong>Miercoles:</strong>
    <%= horario.Miercoles %>
  </p>

  <p>
    <strong>Jueves:</strong>
    <%= horario.Jueves %>
  </p>

  <p>
    <strong>Viernes:</strong>
    <%= horario.Viernes %>
  </p>

  <p>
    <strong>Room:</strong>
    <%= horario.room_id %>
  </p>

</div>

BackEnd-Rails/app/views/horarios/edit.html.erb
<h1>Editing horario</h1>

<%= render "form", horario: @horario %>

<br>

<div>
  <%= link_to "Show this horario", @horario %> |
  <%= link_to "Back to horarios", horarios_path %>
</div>

BackEnd-Rails/app/views/horarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Horarios</h1>

<div id="horarios">
  <% @horarios.each do |horario| %>
    <%= render horario %>
    <p>
      <%= link_to "Show this horario", horario %>
    </p>
  <% end %>
</div>

<%= link_to "New horario", new_horario_path %>

BackEnd-Rails/app/views/horarios/new.html.erb
<h1>New horario</h1>

<%= render "form", horario: @horario %>

<br>

<div>
  <%= link_to "Back to horarios", horarios_path %>
</div>

BackEnd-Rails/app/views/horarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @horario %>

<div>
  <%= link_to "Edit this horario", edit_horario_path(@horario) %> |
  <%= link_to "Back to horarios", horarios_path %>

  <%= button_to "Destroy this horario", @horario, method: :delete %>
</div>